In [3]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [4]:
import pandas as pd
import numpy as np

import datetime

import matplotlib.pyplot as plt
%matplotlib inline

In [5]:
data = pd.read_csv("/content/drive/MyDrive/Feature Engineering/loans_full_schema.csv", usecols=['issue_month'], nrows=1000)

In [6]:
data.head()

  issue_month
0    Mar-2018
1    Feb-2018
2    Feb-2018
3    Jan-2018
4    Mar-2018

In [7]:
data['issue_month_dt'] = pd.to_datetime(data.issue_month)

data[['issue_month', 'issue_month_dt']].head()

  issue_month issue_month_dt
0    Mar-2018     2018-03-01
1    Feb-2018     2018-02-01
2    Feb-2018     2018-02-01
3    Jan-2018     2018-01-01
4    Mar-2018     2018-03-01

In [8]:
# extracting Month from date

data['issue_dt_month'] = data['issue_month_dt'].dt.month
data.head()

  issue_month issue_month_dt  issue_dt_month
0    Mar-2018     2018-03-01               3
1    Feb-2018     2018-02-01               2
2    Feb-2018     2018-02-01               2
3    Jan-2018     2018-01-01               1
4    Mar-2018     2018-03-01               3

In [9]:
# extract quarter from date variable

data['issue_dt_quarter'] = data['issue_month_dt'].dt.quarter
data.head()

  issue_month issue_month_dt  issue_dt_month  issue_dt_quarter
0    Mar-2018     2018-03-01               3                 1
1    Feb-2018     2018-02-01               2                 1
2    Feb-2018     2018-02-01               2                 1
3    Jan-2018     2018-01-01               1                 1
4    Mar-2018     2018-03-01               3                 1

In [10]:
data.issue_dt_month.unique()

array([3, 2, 1])

In [11]:
# extract Semester from date variable

data['issue_dt_semester'] = np.where(data.issue_dt_quarter.isin([1,2]),1,2)
data.head()

  issue_month issue_month_dt  ...  issue_dt_quarter  issue_dt_semester
0    Mar-2018     2018-03-01  ...                 1                  1
1    Feb-2018     2018-02-01  ...                 1                  1
2    Feb-2018     2018-02-01  ...                 1                  1
3    Jan-2018     2018-01-01  ...                 1                  1
4    Mar-2018     2018-03-01  ...                 1                  1

[5 rows x 5 columns]

In [12]:
# day - numeric from 1 -31 

data['issue_dt_day'] = data['issue_month_dt'].dt.day
data.head()

  issue_month issue_month_dt  ...  issue_dt_semester  issue_dt_day
0    Mar-2018     2018-03-01  ...                  1             1
1    Feb-2018     2018-02-01  ...                  1             1
2    Feb-2018     2018-02-01  ...                  1             1
3    Jan-2018     2018-01-01  ...                  1             1
4    Mar-2018     2018-03-01  ...                  1             1

[5 rows x 6 columns]

In [13]:
# day of the week -- from 0 to 6  --> 0 Monday --> 6 Sunday
data['issue_dt_dayofweek'] = data['issue_month_dt'].dt.dayofweek
data.head()

  issue_month issue_month_dt  ...  issue_dt_day  issue_dt_dayofweek
0    Mar-2018     2018-03-01  ...             1                   3
1    Feb-2018     2018-02-01  ...             1                   3
2    Feb-2018     2018-02-01  ...             1                   3
3    Jan-2018     2018-01-01  ...             1                   0
4    Mar-2018     2018-03-01  ...             1                   3

[5 rows x 7 columns]

In [14]:
# week day name
data['issue_dt_namedayofweek'] = data['issue_month_dt'].dt.day_name()
data.head()

  issue_month issue_month_dt  ...  issue_dt_dayofweek  issue_dt_namedayofweek
0    Mar-2018     2018-03-01  ...                   3                Thursday
1    Feb-2018     2018-02-01  ...                   3                Thursday
2    Feb-2018     2018-02-01  ...                   3                Thursday
3    Jan-2018     2018-01-01  ...                   0                  Monday
4    Mar-2018     2018-03-01  ...                   3                Thursday

[5 rows x 8 columns]

In [15]:
# is weekend

data['is_weekend'] = np.where(data['issue_dt_namedayofweek'].isin(['Sunday', 'Saturday']), 1, 0)
data.head()

  issue_month issue_month_dt  ...  issue_dt_namedayofweek  is_weekend
0    Mar-2018     2018-03-01  ...                Thursday           0
1    Feb-2018     2018-02-01  ...                Thursday           0
2    Feb-2018     2018-02-01  ...                Thursday           0
3    Jan-2018     2018-01-01  ...                  Monday           0
4    Mar-2018     2018-03-01  ...                Thursday           0

[5 rows x 9 columns]

In [16]:
# extract year 

data['issue_dt_year'] = data['issue_month_dt'].dt.year
data.head()

  issue_month issue_month_dt  ...  is_weekend  issue_dt_year
0    Mar-2018     2018-03-01  ...           0           2018
1    Feb-2018     2018-02-01  ...           0           2018
2    Feb-2018     2018-02-01  ...           0           2018
3    Jan-2018     2018-01-01  ...           0           2018
4    Mar-2018     2018-03-01  ...           0           2018

[5 rows x 10 columns]

In [17]:
# extract date difference between 2 dates

In [18]:
(data['issue_dt_month'] - data['issue_dt_month'])

0      0
1      0
2      0
3      0
4      0
      ..
995    0
996    0
997    0
998    0
999    0
Name: issue_dt_month, Length: 1000, dtype: int64

In [19]:
datetime.datetime.today() - data['issue_month_dt']

0     1423 days 15:07:24.368502
1     1451 days 15:07:24.368502
2     1451 days 15:07:24.368502
3     1482 days 15:07:24.368502
4     1423 days 15:07:24.368502
                 ...
995   1482 days 15:07:24.368502
996   1451 days 15:07:24.368502
997   1423 days 15:07:24.368502
998   1423 days 15:07:24.368502
999   1423 days 15:07:24.368502
Name: issue_month_dt, Length: 1000, dtype: timedelta64[ns]

In [20]:
(datetime.datetime.today() - data['issue_month_dt']).dt.days.head()

0    1423
1    1451
2    1451
3    1482
4    1423
Name: issue_month_dt, dtype: int64