In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

replacing features with cardinality by frequency or count

Another way to refer to variables that have a multitude of categories, is to call them variables with hight cardinality

In [2]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split

data = pd.read_csv("/content/drive/MyDrive/Feature Engineering/mercedesbenz.csv", usecols=['X1', 'X2', 'X3', 'X4', 'X5', 'X6', 'y'])
data.head()

        y X1  X2 X3 X4 X5 X6
0  130.81  v  at  a  d  u  j
1   88.53  t  av  e  d  y  l
2   76.26  w   n  c  d  x  j
3   80.62  t   n  f  d  x  l
4   78.02  v   n  f  d  h  d

In [ ]:
for col in data.columns[1:]:
    print(col, ':', len(data[col].unique()), ' labels')

X1 : 27  labels
X2 : 44  labels
X3 : 7  labels
X4 : 4  labels
X5 : 29  labels
X6 : 12  labels

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(data[['X1', 'X2', 'X3', 'X4', 'X5', 'X6']], data.y, test_size=0.3, random_state=0)

X_train.shape, X_test.shape

((2946, 6), (1263, 6))

In [ ]:
X_train.X2.value_counts().to_dict()

{'as': 1155,
 'ae': 342,
 'ai': 289,
 'm': 284,
 'ak': 188,
 'r': 101,
 'n': 97,
 's': 63,
 'e': 61,
 'f': 59,
 'aq': 46,
 'ay': 40,
 'a': 34,
 't': 17,
 'k': 16,
 'ag': 15,
 'i': 15,
 'z': 14,
 'b': 12,
 'd': 12,
 'g': 10,
 'ac': 10,
 'ao': 10,
 'y': 8,
 'x': 8,
 'ap': 5,
 'at': 5,
 'h': 4,
 'au': 3,
 'q': 3,
 'an': 3,
 'al': 3,
 'ah': 3,
 'av': 2,
 'aw': 2,
 'c': 1,
 'l': 1,
 'o': 1,
 'aa': 1,
 'af': 1,
 'p': 1,
 'am': 1}

In [ ]:
# create dictionary that maps each label to the counts
X_frequent_map = X_train.X2.value_counts().to_dict()

# replace X2 labels both in the train and test set with the same map
X_train.X2 = X_train.X2.map(X_frequent_map)
X_test.X2 = X_test.X2.map(X_frequent_map)

In [ ]:
X_train.head()

      X1    X2 X3 X4 X5 X6
3059  aa   289  c  d  q  g
3014   b   284  c  d  q  i
3368   o    59  f  d  s  l
2772  aa  1155  d  d  p  j
3383   v    61  c  d  s  g