In [ ]:
from google.colab import drive
drive.mount('/content/drive')

## Replacing labels by the risk factor (the target mean)

replacing labels by the risk factor means essentially replacing the label by the mean of the target for that label.

In [ ]:
import pandas as pd

from sklearn.model_selection import train_test_split

%matplotlib inline

In [ ]:
data = pd.read_csv("/content/drive/MyDrive/Feature Engineering/titanic_train.csv", usecols=['Cabin', 'Survived'])
data.head()

   Survived   Cabin
0         1  C12239
1         0     NaN
2         0     NaN
3         0     NaN
4         1     NaN

In [ ]:
# fill Na values with an additional label 

data.Cabin.fillna('Missing', inplace=True)
data.head()

   Survived    Cabin
0         1   C12239
1         0  Missing
2         0  Missing
3         0  Missing
4         1  Missing

In [ ]:
len(data.Cabin.unique())

26993

In [ ]:
data['Cabin'] =  data['Cabin'].astype(str).str[0]
data.head()

   Survived Cabin
0         1     C
1         0     M
2         0     M
3         0     M
4         1     M

In [ ]:
data.Cabin.unique()

array(['C', 'M', 'A', 'D', 'B', 'E', 'F', 'G', 'T'], dtype=object)

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(data[['Cabin', 'Survived']], data.Survived, test_size=0.3, random_state=0)

X_train.shape, X_test.shape

((70000, 2), (30000, 2))

In [ ]:
X_train.groupby(['Cabin'])['Survived'].mean()

Cabin
A    0.273529
B    0.627943
C    0.709877
D    0.733488
E    0.612613
F    0.830769
G    0.860606
M    0.341836
T    0.520000
Name: Survived, dtype: float64

In [ ]:
ordered_labels = X_train.groupby(['Cabin'])['Survived'].mean().to_dict()
ordered_labels

{'A': 0.2735294117647059,
 'B': 0.6279425837320575,
 'C': 0.7098765432098766,
 'D': 0.7334878331402086,
 'E': 0.6126126126126126,
 'F': 0.8307692307692308,
 'G': 0.8606060606060606,
 'M': 0.3418364122764519,
 'T': 0.52}

In [ ]:
## replace the labels with the ordred numbers 
X_train['Cabin_ordered'] = X_train.Cabin.map(ordered_labels)
X_test['Cabin_ordered'] = X_test.Cabin.map(ordered_labels)

In [ ]:
X_train.head()

      Cabin  Survived  Cabin_ordered
42865     M         0       0.341836
91446     M         0       0.341836
66374     M         0       0.341836
79106     C         0       0.709877
13404     M         1       0.341836