In [ ]:
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
%matplotlib inline

# for regression problems
from sklearn.linear_model import LinearRegression, Ridge

# to split and standarize the dataset
from sklearn.model_selection import train_test_split

# to evaluate regression models
from sklearn.metrics import mean_squared_error

import warnings
warnings.filterwarnings('ignore')

In [ ]:
# load the titanic Dataset with a few variables for demonstration
cols_to_use = ['BsmtQual', 'FireplaceQu', 'GarageType', 'SalePrice']

data = pd.read_csv('../house_price_train.csv', usecols=cols_to_use)
data.isnull().mean().sort_values(ascending=True)

SalePrice      0.000000
BsmtQual       0.025342
GarageType     0.055479
FireplaceQu    0.472603
dtype: float64

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(data[['BsmtQual', 'FireplaceQu', 'GarageType']], data.SalePrice, test_size=0.3,
                                                    random_state=0)
X_train.shape, X_test.shape

((1022, 3), (438, 3))

In [ ]:
def impute_na(df_train, df_test, variable):
    most_frequent_category = df_train.groupby([variable])[variable].count().sort_values(ascending=False).index[0]
    df_train[variable+'_NA'] = np.where(df_train[variable].isnull(), 'Missing', df_train[variable])
    df_test[variable+'_NA'] = np.where(df_test[variable].isnull(), 'Missing', df_test[variable])

In [ ]:
for variable in ['BsmtQual', 'FireplaceQu', 'GarageType']:
    impute_na(X_train, X_test, variable)

In [ ]:
X_train.isnull().sum()

BsmtQual           24
FireplaceQu       478
GarageType         54
BsmtQual_NA         0
FireplaceQu_NA      0
GarageType_NA       0
dtype: int64

In [ ]:
X_train.head()

     BsmtQual FireplaceQu GarageType BsmtQual_NA FireplaceQu_NA GarageType_NA
64         Gd         NaN     Attchd          Gd        Missing        Attchd
682        Gd          Gd     Attchd          Gd             Gd        Attchd
960        TA         NaN        NaN          TA        Missing       Missing
1384       TA         NaN     Detchd          TA        Missing        Detchd
1100       TA         NaN     Detchd          TA        Missing        Detchd